config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root "posts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end 

  def destroy
    @post.destroy
    redirect_to root_path
  end


  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
    <br>
    <%= f.label :body %><br>
    <%= f.text_area :body %><br>
    <br>
    <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit "<%= @post.title %>"</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<%= link_to "Write New", new_post_path %>

<% @posts.each do |post| %>
     <h1><%= post.title %></h1>
     <p><%= truncate(post.body, :length => 35) %></p>
    <%= link_to "Read Post", post %>
<% end %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>
<p>Here we will have a form to create a new post</p>

<%= render 'form' %>

app/views/posts/show.html.erb
    <div class="col-md-4">
     <h1><%= @post.title %></h1>
     <p><%= @post.body %></p>
    </div>
    <%= link_to 'Edit Post', edit_post_path(@post) %>
    <br>
    <%= link_to 'Delete Post', post_path(@post), method: :delete, data: {confirm: "Sure you want to delete this post?"} %>
    <br>
    <%= link_to 'Home', root_path %>